from .core import run_all
from .test_legacy import *
from .test_sop import *
from .test_temporal import *
from .test_architecture import *
from .test_artifacts import *
from .test_code import *
from .test_data import *
from .test_math import *
from .test_consistency import *
from .test_env import *
from .test_r14_fixes import *
from .test_v5_bugs import *
from .test_invariants import *